### ISSUE TITLE
Make the user profile storable

### ISSUE THREAD

**Issue by BoBoBaSs84** [BoBoBaSs84/BB84.SAU#12]
**Is your feature request related to a problem? Please describe.**
The complete data has to be loaded every time the program is started, which takes a lot of time here and there.

**Describe the solution you'd like**
If nothing has changed in the user profile, the games or the achievements, the data does not have to be reloaded, but can be reloaded if necessary.

**Describe alternatives you've considered**
Waiting time.

**Additional context**
Maybe save the data in a JSON or in an XML as application data ...

**Comment by Probotus** [comment]
That would be cool, only loading when needed.
