### ISSUE TITLE
Application Logbook

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.SAU#14]
**Is your feature request related to a problem? Please describe.**
I get an error message every time I load my games. The error message pops up briefly in the status bar, but it is too fast to read.

**Describe the solution you'd like**
Would it be possible to have a kind of logbook in the application?

**Describe alternatives you've considered**
Living with the error without knowing what it actually is.

**Comment by BoBoBaSs84** [comment]
I have a similar issue, I think this happens if you have content that is not a game. Like tools or so...

But yeah, the idea is cool.
