### ISSUE TITLE
Small Fixes

### ISSUE THREAD

**Issue by BoBoBaSs84** [BoBoBaSs84/BB84.SAU#23]
**Describe the Issue**
- The year property is not correct
- The read me has errors in it
- fix some mismatches in method names and models
- fix method names that are async

**Comment by Probotus** [comment]
There is also a miss match between method names and return type:
- [here](https://github.com/BoBoBaSs84/BB84.SAU/blob/main/src/BB84.SAU.Domain/Models/UserDataModel.cs)
- and [here](https://github.com/BoBoBaSs84/BB84.SAU/blob/main/src/BB84.SAU.Application/Services/SteamWebService.cs)

**Comment by BoBoBaSs84** [comment]
You are right. The method name `GetUserProfile` should be `GetUserData`. Thx
