### ISSUE TITLE
Overall achievement progress not working

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.SAU#37]
**Describe the bug**
The progress bar” does not work properly / does not update properly.

**To Reproduce**
1. Select a game
2. Go to achievements
3. Unlock achievement
4. See error -> no change in progress

**Expected behavior**
Progress should change.

**Comment by BoBoBaSs84** [comment]
Jup, that's a bug. I assigned you, so can you have a look into it?
