### ISSUE TITLE
docs: start the wiki

### ISSUE THREAD

**Issue by BoBoBaSs84** [BoBoBaSs84/BB84.SAU#4]
**Is your feature request related to a problem? Please describe.**
No one knows how to use it ...

**Describe the solution you'd like**
Start the wiki

**Describe alternatives you've considered**
None.

**Comment by Probotus** [comment]
Where can I get an API key?

**Comment by Probotus** [comment]
Okay, found it [here](https://steamcommunity.com/dev/apikey).

**Comment by BoBoBaSs84** [comment]
The issue is obviously created for a reason ;)
