### ISSUE TITLE
`Lock` and `Unlock` buttons not alternating

### ISSUE THREAD

**Issue by Probotus** [BoBoBaSs84/BB84.SAU#8]
**Describe the bug**
When you unlock an achievement, the buttons are not updated.

**To Reproduce**
1. Go to `Achievments`
2. Select one achievement to unlock
3. Click on the `Unlock` button

**Expected behavior**
The behavior should be such that the buttons alternate back and forth depending on whether the achievement is unlocked or locked.

**Comment by BoBoBaSs84** [comment]
I was able to reproduce the error, you just have to listen for the event that is called when the achievement is unlocked or locked.

I'll take a look at this in detail tomorrow.
